### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by luckashish** [kambalatech/NorenApiPySample#2]
hi facing problem to login (properly interned all parameters in file cred.yml )

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): kurma.kambala.co.in:9959
DEBUG:urllib3.connectionpool:http://kurma.kambala.co.in:9959 "POST /NorenWClient//QuickAuth HTTP/1.1" 400 63
DEBUG:NorenRestApiPy.NorenApi:Reply:{"stat":"Not_Ok","emsg":"Invalid Input :  Invalid Vendor code"}

**Comment by hola101010** [comment]
how you obtain your API credentials?

**Comment by luckashish** [comment]
hi from broker (finvasia)

**Comment by luckashish** [comment]
Hi now i am able to login ( if any one is getting this error "Invalid Input : User Not enabled on : API" call you broker they will enable it)

how to close API session please tell
